version: '2'
services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=revel
            - MYSQL_USER=revel
            - MYSQL_PASSWORD=secret
    web:
        build: .
        command: revel run myapp
        volumes:
            - ./myapp:/go/src/myapp
        ports:
            - 9000:9000
        depends_on:
            - db
    pma:
        image: phpmyadmin/phpmyadmin
        environment:
                - PMA_ARBITRARY=1
                - PMA_HOST=db
                - PMA_USER=revel
                - PMA_PASSWORD=secret
        links:
                - db
        ports:
                - 8080:80
